### PR TITLE
Create Defines.dsc.inc

### PR DESCRIPTION
**Pull request by Ost268**

### CODE REVIEW

**Comment by sunflower2333** [comment]
Well your commits......
And you missed many things such as dtb or PcdsFixedAtBuild.dsc.inc
If you want a guide, see a simpleguide [here](https://github.com/woa-msmnile/MU-sm8150pkg/blob/main/Documentation/SimpleGuide.md).

**Comment by sunflower2333** [comment]
uh, I wanna to know, have you tested it ?

**Comment by Ost268** [comment]
I will test on Sunday, then I will give an answer

czw., 24 lis 2022, 14:17 użytkownik sunflower2333 ***@***.***>
napisał:

**Comment by qaz6750** [comment]
I wonder why it contains so many commits?

**Comment by qaz6750** [comment]
image
Even these. It can be turned into a commit

**Comment by Ost268** [comment]
Turn off commit

czw., 1 gru 2022, 15:27 użytkownik lzy2835 ***@***.***>
napisał:

**Pull request closed without merging**
