### PR TITLE
Update/2405

### PR DESCRIPTION
**Pull request by gus33000**
Rebase repository on the latest upstream code.

The latest code allows for more modularity regarding configuration maps

### CODE REVIEW

**Comment by gus33000** [comment]
Note: Don't merge just yet as a few devices still need to be migrated.

Worth pointing out a lot of devices never actually used their uefiplat.cfg for creating the configuration map headers. Im migrating those as is but at the same time it was very obvious when they include microsoft surface duo hob addr values...

**Comment by gus33000** [comment]
Note: This also adds support for MTP 8150 directly

**Comment by gus33000** [comment]
PR compiles fine for 8150, other variants untested for compilation
Functionality remains untested

**Comment by gus33000** [comment]
S-Error on MTP8150-AC (Hercules)

**Comment by mohahack** [comment]
guacamole stopped on fastboot after boot uefi

**Comment by mohahack** [comment]
Guacamole error photo

**Comment by gus33000** [comment]
The update is nowhere near ready to be merged or functional, we know about this already. Stick to stable releases from the release page. This is not intended to be consumed just yet 👍

**Comment by sunflower2333** [comment]
need a new way to pass display address in memory map to framebuffer serial library, 
Hob does not work. also pcd is not acceptable in this case..

**Comment by gus33000** [comment]
PASS: https://github.com/woa-msmnile/msmnilePkg/actions/runs/9554518500

With workaround for the new config / mem map libs (we force the sec ones in, which equals to the old behavior entirely, no hob)

**Comment by gus33000** [comment]
Artefacts as part of the test run are only available for a few days, if anyone want to test, feel free while time allows.

**Comment by gus33000** [comment]
image
We may need to fix the kona zip name though..

**Comment by gus33000** [comment]
Failure observed as well:

`No files were found with the provided path: Build/LahainaPkg/ci_artifacts. No artifacts will be uploaded.`

And indeed, no 8350 zip file dropped, need investigation as to why it looks up this path and not the correct one (SurfaceDuo2Pkg)

**Comment by gus33000** [comment]
lgtm, i guess this can be merged if you want to

**Comment by sunflower2333** [comment]
@gus33000 have to merge main into new br becuase new devices/changes were added in this period.

**Pull request merged**
