### PR TITLE
add translation RU,UA,PL

### PR DESCRIPTION
**Pull request by Ost268**

### CODE REVIEW

**Comment by AistopGit** [comment]
@Ost268 wouldn't say google translate did good, at least with russian it did not

**Comment by Ost268** [comment]
> @Ost268 wouldn't say google translate did good, at least with russian it did not
I will fixed with time, so that there are no stupid questions on the forums

**Comment by sunflower2333** [comment]
@Ost268 Thank you a lot. Btw Docs are moved to 
https://github.com/woa-msmnile/woa-msmnile.github.io

**Comment by sunflower2333** [comment]
Hello, please reply ''finined'' here if you have finished, thanks

**Comment by Ost268** [comment]
Ok no problem mr.sunflower2333

**Comment by sunflower2333** [comment]
Sir Please withdraw your commit of Lahaina in this pr

**Comment by sunflower2333** [comment]
You should open a branch for pr and develop lahaina in another branch. Otherwise it will show here.
Create a new branch(eg lahaina) from your current main, then go back to main, checkout it to the end of    
where it should be(e.g.  81f2d31), and force push to main.
If you do not do this, we'll close the pr. Please tell me if you meet any issue.

**Review by sunflower2333 — CHANGES_REQUESTED** [review]
Example:
Cut pr to the commit before here.

**Comment by sunflower2333** [comment]
@sunflower2333 Ost268 i wonder if you do not check github emails?🤔

**Comment by gus33000** [comment]
Please stop pushing commits related to 8350 here. This PR is about updating the documentation only. We will have to close this PR unfortunately if it continues.

**Comment by gus33000** [comment]
Closed. Please create a new pr if you want to add support for another device. Please create a different pr for documentation update. But please do not stitch a ton of changes in the same pr and deviate from the original goal.

**Pull request closed without merging**
