### PR TITLE
add device tree samsung-winner

### PR DESCRIPTION
**Pull request by Ost268**

### CODE REVIEW

**Comment by leandrofriedrich** [comment]
I am by no means able to control what happens here or force you but please, do everyone a favor and squash those commits into a few less commits

**Comment by sunflower2333** [comment]
hi bro, check the line in readme.md: | samsung-winner | xxx | xxx | xxx |

**Comment by sunflower2333** [comment]
all things looks fine now, thanks for pr.

**Comment by sunflower2333** [comment]
please reply me if you still have something to add, otherwise this pr will be merged in 24hours.

**Comment by Ost268** [comment]
Hi bro, thanks fo commit, I will update dtb in the evening
sob., 23 wrz 2023, 03:06 użytkownik Kancy Joe ***@***.***>
napisał:

**Comment by Ost268** [comment]
Hi bro  the same problem for build (nuget installed,
 mono installed)



sob., 23 wrz 2023, 08:19 użytkownik Igor Ostrovskyy ***@***.***>
napisał:

**Comment by sunflower2333** [comment]
u can just build all 8150 devices in github action actually

Sunflower2333.
________________________________

**Comment by sunflower2333** [comment]
i think you should add these commits in next pr

**Pull request merged**
