### PR TITLE
7125: miatoll: Update DSDT and more fixes

### PR DESCRIPTION
**Pull request by N1kroks**

### CODE REVIEW

**Comment by sunflower2333** [comment]
Review pass.
If it's ready for merge please reply yes.
Thanks for contribution.

**Comment by NetuserPRO** [comment]
where does the displaydxe come from?

**Comment by N1kroks** [comment]
> where does the displaydxe come from?

I patched it

**Comment by sunflower2333** [comment]
you can just strings it to get compile path.
```
/home/work/data/miui_codes/release-build-home/vendor/vendor/qcom/non-hlos-2019-spf21/BOOT.XF.3.1/boot_images/Build/RennellLA_Core/RELEASE_CLANG40LINUX/AARCH64/QcomPkg/Drivers/DisplayDxe/DisplayDxe/DEBUG/DisplayDxe.dll
```
Sunflower2333.
________________________________

**Pull request merged**
