### PR TITLE
8150:mh2lm: Update acpi and DeviceTreeBlob

### PR DESCRIPTION
**Pull request by Icesito68**
Now the audio works, some MicroSds stay connected and you can boot Windows (before it stayed in crash dump)

### CODE REVIEW

**Comment by NetuserPRO** [comment]
where did you get the linux dtb? @Icesito68

**Comment by Icesito68** [comment]
I have it months ago, I don't remember if someone sent me lol, I was simply in an old repository of msmnile, maybe it is even outdated.

Anyway I have not tried if the current one works, a moment, I forgot before making the change

**Comment by Icesito68** [comment]
I confirm that the one that was before can be used

**Comment by sunflower2333** [comment]
If pr is ready to merge please reply me 'Yes' :)

**Comment by Icesito68** [comment]
Yes, hehe

**Comment by dj-ti** [comment]
Bluetooth driver doesn't work on lg-mh2lm after Windows installation. On the previous version everything works fine.

**Comment by n00b69** [comment]
> Bluetooth driver doesn't work on lg-mh2lm after Windows installation. On the previous version everything works fine.

Use the drivers in the github guide

**Comment by dj-ti** [comment]
Thanks for the quick response. Actually after the change the Bluetooth works fine, the error of the disappearing SD card has also been fixed. However, I have noticed that the mini jack does not activate when headphones are inserted. Maybe I am doing something wrong. I also have Virtual Audio Cable on board but this doesn't seem to be causing the problems.

**Comment by dj-ti** [comment]
> > Bluetooth driver doesn't work on lg-mh2lm after Windows installation. On the previous version everything works fine.
> 
> Use the drivers in the github guide

Thanks for the quick response. Actually after the change the Bluetooth works fine, the error of the disappearing SD card has also been fixed. However, I have noticed that the mini jack does not activate when headphones are inserted. Maybe I am doing something wrong. I also have Virtual Audio Cable on board but this doesn't seem to be causing the problems.

**Comment by dj-ti** [comment]
> > > Bluetooth driver doesn't work on lg-mh2lm after Windows installation. On the previous version everything works fine.
> > 
> > 
> > Use the drivers in the github guide
> 
> Thanks for the quick response. Actually after the change the Bluetooth works fine, the error of the disappearing SD card has also been fixed. However, I have noticed that the mini jack does not activate when headphones are inserted. Maybe I am doing something wrong. I also have Virtual Audio Cable on board but this doesn't seem to be causing the problems.

The jack socket works but only with 3-pin headphones, it is not possible to plug in headphones with a 4-pin microphone (they are not detected).

**Pull request merged**
