### PR TITLE
Add nubia SDM845 Device

### PR DESCRIPTION
**Pull request by ghost**
Add nubia SDM845 Device

### CODE REVIEW

**Comment by sunflower2333** [comment]
Hi, please also upload extracted binaries and unextracted xbl(optional) [here](https://github.com/Project-Aloha/BinariesBackup), and fill this following questions, thanks a lot!

1. Can it boot windows without extra drivers installed?
2. Where the DSDT from, leaked souce, decompile existed prototype's , or copied from edk2-msm?
3. Do your commit have self-compiled efis or any codes/binaries from mu-silicium or edk-msm without marking license(memory map,configuration map etc)?

We'll start reviewing after reciving you reply, thanks again. :)

**Comment by ghost** [comment]
1. Yes, Windows can be booted without a driver
2. The DSDT prototype is the Galaxybook-2, which references the DSDT of the Matebook-E-2019, YOGA-C630, HDK845 of the project 625A0B45
3. The binaries are all HDK845 in project 625A0B45

**Comment by Daniel224455** [comment]
Why are folders renamed from Sdm845 to SDM845? this change is unnecessary since every soc is called for ex. Sm8150 and not SM8150
also, ABL pcd should be "napali" not "SDM845"
and fix your memorymap, it looks gore

**Comment by sunflower2333** [comment]
Uh fine, you closed it.
But i'm curious what is project 625A0B45?? I can't get any result about it on gh and google.

**Comment by ghost** [comment]
https://github.com/Project-Aloha/mu_aloha_platforms/tree/625a0b45

**Pull request closed without merging**
